### ISSUE TITLE
Audible navigation instructions

### ISSUE THREAD

**Issue by PhilippMatthes** [priobike/priobike-flutter-app#625]

**Comment by PaulPickhardt** [comment]
The main blocker for this feature is the navigation instruction creation which is a challenge for cyclists. The complexity of crossings and options is greater for cyclists than for cars. The underlying map data source "DRN" currently has problems setting the correct street name.  Instruction generation heavily depends on correct street names. DRN has significant advantages over OSM and is therefore set as default in the app. This means, that this feature stays blocked right now.

We first have to create good navigation instructions. 
Then we can solve issues in the concept of the auditive speed advisory.

**Comment by PhilippMatthes** [comment]
@PaulPickhardt do you consider this blocked our should we open another issue that focuses on removing the navigation instruction part, keeping only the speed advisory part?

**Comment by adeveloper-wq** [comment]
Blocked until the DRN data foundation problems are fixed. New ticket for audible speed advisory: https://github.com/orgs/priobike/projects/1/views/1?pane=issue&itemId=71730915
