### ISSUE TITLE
Update store IDs for App and Playstore Feedback

### ISSUE THREAD

**Issue by adeveloper-wq** [priobike/priobike-flutter-app#633]

**Comment by adeveloper-wq** [comment]
For Playstore it should already be the correct one. In the App store we can update it once it got published there (after release).

**Comment by PaulPickhardt** [comment]
For iOS the apple id also did not change. So, we can close this issue after testing it, when the app is published in the appstore.

**Comment by PhilippMatthes** [comment]
I tested the feature again and did not find any issues rating the app.
